nelmio_cors:
    defaults:
        allow_credentials: false
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['X-Requested-With', 'Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        expose_headers: ['Link']
        hosts: []
        max_age: 3600
        forced_allow_origin_value: ~
